services:
  redis:
    image: redis:7.0.15
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: ${REDIS_PORT}
        protocol: tcp
        mode: host
    volumes:
      - api_redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  api_redis_data:
